# See 02-workflow-events/README.md for more information
# about different triggers for GitHub Actions.

name: Workflow

on: push
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
        working-directory: ga-app/react-app
